name: Keepalive Workflow

on:
  schedule:
    - cron: '0 12 1,15 * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v7
      - uses: liskin/gh-workflow-keepalive@v1
